kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    image: debian:buster
    environment:
      USERNAME:
        from_secret: docker_username
    commands:
      - echo hellosa
      - echo world
      - echo docker_username
      - echo $docker_username
      - echo $USERNAME
      - docker run --rm -ti --name nginx nginx:alpine
