kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: plugins/docker
    environment:
      USERNAME:
        from_secret: docker_username
    settings:
      username: afnia
      password: kopet1234
      repo: afnia/kontol
      build_args:
        - HTTP_PROXY=http://yourproxy.com
