kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: alpine
    environment:
      GIT:
        from_secret: git
    commands:
      - apk add git
      - git clone $GIT

  - name: docker
    image: plugins/docker
    environment:
      DUSER:
        from_secret: docker_username
      DPASSW:
        from_secret: docker_password
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: afnia/kontol
      build_args_from_env:
        - DUSER
      dockerfile: jorjoran_api/Dockerfile
