kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: plugins/docker
    environment:
      DUSER:
        from_secret: docker_username
      DPASSW:
        from_secret: docker_password
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: afnia/kontol
      build_args_from_env:
        - DUSER
