kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: plugins/docker
    environment:
      DUSER:
        from_secret: docker_username
      DPASSW:
        from_secret: docker_password
    settings:
      username: DUSER
      password: DPASSW
      repo: afnia/kontol
      build_args_from_env:
        - DUSER
