kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    image: alpine
    environment:
    USERNAME:
      from_secret: docker_username
    commands:
      - echo hellosa
      - echo world
      - echo docker_username
      - echo $docker_username
      - export
