kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    image: alpine
    commands:
      - echo hellosa
      - echo world
      - echo $KOPET
      - echo $SEMPAK
      - echo 'as'
