kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: debian:buster
    environment:
      GIT:
        from_secret: git
    commands:
      - echo hello
      - echo world
      - echo $USERNAME
      - git clone $GIT
      - ls

  - name: docker
    image: plugins/docker
    environment:
      DUSER:
        from_secret: docker_username
      DPASSW:
        from_secret: docker_password
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: afnia/kontol
      build_args_from_env:
        - DUSER
